### ISSUE TITLE
Tightened security settings from IG: Flagged as a bot/Locked accounts

### ISSUE THREAD

**Issue by quietsecret123** [AssetKid/raider-release#67]
### EDIT (added Dec 6, 2020): This appears to be an issue due to tightened security updates by IG (since it is occurring across multiple apps that scrape the site, such as [4K Stogram](https://github.com/AssetKid/raider-release/issues/67#issuecomment-730623607) and [Instaloader](https://github.com/AssetKid/raider-release/issues/67#issuecomment-739587004)). It's not actually a bug from Raider, per se. However, I am keeping this thread in the hope that we can identify any risk factors (whether or not it is due to user settings on the app) and/or find a solution together somehow 👍

======== ORIGINAL POST BELOW ==========

I'm expanding on closed issue #66

I have a few IG accounts, so I've managed to avoid being rate-limited for the past year now. I have separated my subscription lists into various acc files and alternate between using different accounts to avoid being rate-limited. Even though I continue to avoid being rate-limited, now IG has been randomly "logging me out" (for lack of a better term) partway through my downloads and they show up as "failed". When I try to log back in, they ask for a phone number and/or a verification code, even if I don't use 2-factor authentication. This has happened multiple times to the same accounts now, so some of my accounts are now being disabled (while others continue to be "revived").

Not sure if this is happening to other users of Raider recently, or if this describes the same lockout that @avekifes was bringing up.

I know @KaunWho suggested expanding the mass update sleep timer to 50-100 seconds... but frankly I follow too many accounts that 24 hours won't be enough to go through my subscription list if I make the mass update sleep timer that long... 

Any other suggestions?

*I've also tried making more IG accounts, and those attempts are also getting thwarted. I tried to see if using a VPN reduces the likelihood of being flagged, but it doesn't seem to be effective either.

**Comment by Mintonne** [comment]
Do you also use the Instagram app or site for day to day browsing?

**Comment by supersick123** [comment]
I don't browse the site or use the app for those "extra" accounts. Their purpose, on creation last year, was to simply to avoid being rate-limited when the prohibitive rate limits came out in Aug 2019. I think @AssetKid mentioned "heavy Instagram users" are more likely to get blocked, so these accounts are the complete opposite. I wonder if that also might be why (potentially suspicious inactivity). 

For some of them, I followed a few accounts to make it seem like they have a purpose, since 0 followers, 0 followed and 0 posts (which I will call zero stats) looks odd. As I look back on the list now, it seems many of the disabled ones have zero stats, while the ones more likely to recover from being flagged do have stats. That being said, even those with stats do get flagged for suspicious activity and require re-verification. Even one of the alternate accounts that I use regularly to follow locked accounts (which I only do when Raider is downloading with another account) got flagged.

Historically, IG has disabled 2 of my accounts for "suspicious activity"... but it usually takes months before this happens. Now, it seems to be occurring everyday, multiple times a day, for many accounts. It seems this is the new "rate limit", while the old rate limit has been lifted (I noticed each account is now capable of downloading a greater number of accounts than before, when historically the rate limit error message would appear)

When I used to use 4kStogram, my strategy was to use 1 account to download 15-20 accounts, then logout and switch to another account and download 15-20 accounts and so forth. Nothing got flagged, but it was a time-consuming manual process that took 9 hours in total. I don't think Raider has an automated way of doing this as of last year. I would have to manually make acc lists of 15-20 and do what I used to do with 4KStogram. Raider's automation is ultimately what led me to ditch 4kStogram, so manually going back to the old way would be defeating my purpose.

@KaunWho mentioned the mass update sleep timer should be made higher (50-100 seconds) to simulate a human, and the above paragraph is the only solution I can think of right now that would functionally accomplish this while still being "fast" enough to work for those of us who follow thousands of accounts. 

A feature where Raider downloads followed account A with login account 1, then followed account B with login account 2, then followed account C with login account 3, then followed account D with login account 1 (starts over) would probably help us bypass the current limits. I think the framework is already partially there. Raider allows multiple accounts to be logged in (unlike 4K Stogram) and is able to "switch" between accounts when it hits a roadblock. When an error occurs (e.g. a locked followed account), I believe it goes down the list of logins to see which logged in account would bypass the error in the end (up to 5 attempts, I think). However, this type of modification is a big ask, so not sure how much time @AssetKid is able to devote to this (or if there's any interest).

**Comment by supersick123** [comment]
Seems this issue is more widespread than I thought...

IG has been tightening its security, and it is happening with other apps as well.

https://www.reddit.com/r/4kdownloadapps/comments/i8095k/instagram_permanently_banning_accounts_associated/
https://www.reddit.com/r/4kdownloadapps/comments/jw1d0p/4kstogram_account_deactivations_whats_the_issue/

There are more posts/comments on the same topic in that subreddit as well, but you get the point.

**Comment by logan478** [comment]
Hello, i have same problem and my suggestion is download only stories with 5 seconds delay, because this will not hit limit or make you blocked and only stories will be lost after 24 hours. Then delete account from raider and download images and videos with 5 seconds delay without account, so it will not block your account. Thats how i am doing it right now and no problems.

**Comment by supersick123** [comment]
> Hello, i have same problem and my suggestion is download only stories with 5 seconds delay, because this will not hit limit or make you blocked and only stories will be lost after 24 hours. Then delete account from raider and download images and videos with 5 seconds delay without account, so it will not block your account. Thats how i am doing it right now and no problems.

Thank you for your suggestion. I've tried what you initially suggested (5 second delay, only stories) and it *seems* to be mostly working... as long as the same account isn't more than once in 24 hours (which was an existing rule during the rate-limiting days). I guess there's less API calls involved, so it's less suspicious in hitting the threshold. I'll have to keep observing and testing, and I might still have to lengthen the delay (to maybe 15-30 seconds?) as you and others have said.

> EDIT: okay today after 3 days it locked my account when downloading just stories. So i suggest you to increase delay when downloading only stories, because 5 seconds is not enough.

If I may ask, what is the file size of your acc file if it gets blocked, ie how many accounts are you trying to download? I think there is a new, lower threshold for API calls, but I'm trying to figure out what that is. I'm usually safe if my acc file is around 35-38kb or less (350+ accounts, less than 400). If the acc file is around 42-44kb (450-470 accounts), I *sometimes* get locked out before it is complete... but weirdly around the halfway mark (around account 180-220).

**Comment by logan478** [comment]
Its for sure about API again. Stories are using just one API request per account, so its not hitting limit, but even then after 3 days i got blocked when using 5 seconds delay, so i am gonna try 10 seconds now. 

About accounts, i am updating about 780 subscriptions every 24 hours. Thats why 100 seconds delay is not possible because i cant let run my PC more than 24 hours, and i will lost stories for example. So stories with 5 seconds was okay for 3 days. After 3 days i got blocked in middle of updating and it showed just failed numbers.. My acc file have 71,6 kb.  

Whole problem i think is that we should do less API requests on accounts, ale other things download without account.

**Comment by denbartman** [comment]
Hi,
Same problem here. One of my accounts gets locked every few days an i have to generate a new password.
* I have a few instagram accounts. 
* Each account has about 50-100 open users accounts it follows.
* Each account also has a few (<10) private account it follows.
* I'm a little scared that my accounts with access to private user accounts get locked forever...
* Could the following be a solution:
   * Link the sites to scrape to an account (so that only private sites get scraped by my accounts)
   * Non private accounts could be scraped without logging in, or by extra created dummy accounts for witch it is not so bad if they get locked for ever... 

Any thoughts on this AssetKid? Or are you thinking of an other solution?

kind regards and thanx for the great work...

**Comment by supersick123** [comment]
So a lot has happened and changed in the last 2.5 weeks that I couldn't even keep track anymore. However, here are some of the security measures IG has thrown at me lately and some other observations:

- As previously mentioned, they will sometimes mark me for "suspicious activity" and "temporarily lock" my account _halfway through the download_ because they believe I've been phished. This usually requires them to email me a 6-digit verification code, which has to be typed in. Sometimes, it asks for a password change, sometimes it does not. I've changed my password so many times now in the past 2-3 weeks that it's getting hard to keep track. After that, I log back in, and downloading can resume.

<img width="1000" alt="Screen Shot 2020-12-06 at 8 13 53 AM copy" src="https://user-images.githubusercontent.com/63994830/101292338-db294f00-37c3-11eb-8b49-074d771a30ed.png">

<img width="1000" alt="Screen Shot 2020-12-06 at 8 14 01 AM copy" src="https://user-images.githubusercontent.com/63994830/101292389-ff852b80-37c3-11eb-9b57-f0a1b0a98ccc.png">

- Recently, some of my accounts have been getting flagged at the _first login_. Oddly enough, this only happens when trying to login using Raider; logging in through the normal browser does NOT get flagged for suspicious activity. This takes place before any downloads have happened (ie. the account hasn't been used in 24 hours, but has definitely been used within the last 30 hours). It'll say "suspicious activity detected" in a red banner, then prompt to send a verification code. I sadly don't have a screenshot of this right now (and I'm lucky it hasn't happened since this morning), but the warning looks different than the above. Once you write the verification code, IG will let you proceed. However, sometimes when the popup/login window is closed after, the cookie(?) doesn't save (seems to be a recurring issue since May), and you have to login all over, repeating the same steps. I'm pretty sure this makes IG even more suspicious since someone wouldn't login multiple times if their first login is successful. They probably think the account is being hacked? I tried a VPN to see if flagging for "suspicious activity" might be linked to an IP address, but it didn't change anything.

- It definitely has a link to API calls [as @logan478 mentioned](https://github.com/AssetKid/raider-release/issues/67#issuecomment-731729645). Accounts are less likely to get flagged/locked/marked as suspicious/any of the above when they are just downloading stories vs stories + images. However, even if you just download stories, the account will eventually also get flagged, [as also previously cited by @logan478](https://github.com/AssetKid/raider-release/issues/67#issuecomment-731616068). 

- In light of the above, @logan478 suggested downloading images while not logged in. I tried that, but it seems there's also a "rate limit" for IP addresses. I know when I open a lot of profiles in my browser while logged out, it'll stop loading when I get to 100 profiles or something (arbitrary number), then force me to login. Take a look at this screenshot, only images/vids are being downloaded and I made sure no account is logged in, but 80 of them failed somehow (and they all download when an account is signed in). I think that's what's happening here. If not, maybe someone can make sense of it for me.

<img width="704" alt="Screen Shot 2020-12-03 at 12 37 33 AM copy" src="https://user-images.githubusercontent.com/63994830/101292724-2b091580-37c6-11eb-8e6d-524c2914e3b1.png">

- Perhaps the most concerning of all is IG deactivates some of the flagged accounts in the end, which means you're losing capacity to work around the rate limit or follow some private accounts, [as @denbartman wrote above](https://github.com/AssetKid/raider-release/issues/67#issuecomment-738448966). The deactivated accounts I had this week were previously the ones with the "red" suspicious activity warning (even if you pass all the tests and prove it's you and you can download again). When you login one day, you get this screen, and when you click "get help", it takes you to this page: https://help.instagram.com/358911864194456. This account is basically lost.

Starting today, I have lengthened the wait interval to 15 seconds instead of 5 seconds between accounts. It might help a bit, but I'm not keeping my hopes up, [based on this comment someone else had made on Reddit](https://www.reddit.com/r/4kdownloadapps/comments/jw1d0p/4kstogram_account_deactivations_whats_the_issue/gco9y7l/?utm_source=reddit&utm_medium=web2x&context=3). I know it's not the 100 seconds that was previously suggested by @KaunWho, but I definitely wouldn't be able to do longer than this without missing stories. 

I, along with others, am still actively looking for solutions, meanwhile. Please feel free to share your observations/similar experiences/thoughts on the matter. We can pool our knowledge together and work through this!

**Comment by supersick123** [comment]
> Its for sure about API again. Stories are using just one API request per account, so its not hitting limit, but even then after 3 days i got blocked when using 5 seconds delay, so i am gonna try 10 seconds now.

How's your trial at 10 seconds? Are you still getting flagged?

> About accounts, i am updating about 780 subscriptions every 24 hours. Thats why 100 seconds delay is not possible because i cant let run my PC more than 24 hours, and i will lost stories for example. So stories with 5 seconds were okay for 3 days. After 3 days i got blocked in middle of updating and it showed just failed numbers.. My acc file have 71,6 kb.

Do you have 2-3 accounts? I think 71.6kb/780 subscriptions for 1 account is too much. I used to get rate limited back then. I found that 45kb is the max I can go (around 450-475 subscriptions). The accounts that are least likely to get flagged for me are the ones that a) get used less than 24 hours AND b) download ~35kb (<400 subscriptions). However, even one of my accounts, which I use to follow <250 private accounts (~20kb), gets flagged if I download both images and stories.

> Whole problem i think is that we should do less API requests on accounts, and other things download without account.

**Comment by logan478** [comment]
Honestly i am sad because i literally tried everything. 10 seconds was better than 5 but still flagged and i dont want to increase it more. I have 2 accounts. One with some private profiles and other one without anything. First i download stories with empty account and then with private account those few which are private. Images and videos i download without account and never had IP rate limit. Failed are for me just those accounts which are private. But honestly this security is too much :( I had never seen anything so strict. Even without using Raider just logging in into Instagram i must always put verification code. Its so annoying. So i am getting locked account and always must verify it. If they lock my empty account, i dont care. I cant wait whole day to download everything. With 5 seconds it took me 1,5 hour and with more even 10 hours. Its crazy...

**Comment by supersick123** [comment]
> But honestly this security is too much :( I had never seen anything so strict.

IG deserves some congratulations... they've done it well this time. I'm pretty sad about it too since people also put interesting stories, which I like looking back on and saving, but it's getting more and more difficult with the new security updates.

> If they lock my empty account, i dont care. 

Same with me, since they're just useless accounts. However, I'm also running out of "empty" accounts to use, and IG has made it harder to create new accounts, so this is why I'm getting concerned. 

> I cant wait whole day to download everything. With 5 seconds it took me 1,5 hour and with more even 10 hours.

Yeah, 10 hours is a lot. I'm going through the same thing right now. I usually just leave my computer on and let it work on its own.

Hopefully @AssetKid has new solutions?

**Comment by supersick123** [comment]
Also, I know some websites let you download stories if you type in the person's username. I wonder how they do it, since they don't require us to login at all (ie our current problem). 

I'm sure if it was possible, @AssetKid would've already made it happen :( I'm sure it's a requirement somehow, since Instaloader and 4K Stogram all require a login as well.

**Comment by logan478** [comment]
I had seen some of them have even much higher resolution of pictures/videos, i dont know where they get that from. I was using 4K Stogram and it was terrible, huge RAM consumption, crashing. Raider is the best so far...

**Comment by supersick123** [comment]
> I had seen some of them have even much higher resolution of pictures/videos, i dont know where they get that from. I was using 4K Stogram and it was terrible, huge RAM consumption, crashing. Raider is the best so far...

Yeah, I noticed some others can pull higher resolutions, but I think AssetKid mentioned that it uses the web API and therefore maxxes out at the current resolution. I could be wrong, but I remember reading something like this.

I agree with you 100%. I formerly used 4K Stogram, and Raider is leaps and bounds better. Raider is more stable than 4K Stogram and easy-to-use for someone like me who doesn't know how to use scripts like Python (vs Instaloader linked below). It has helped me so much since I started using it in May.

I know this thread is basically a complaint, but this issue is definitely a problem from IG. We both know it's NOT because Raider, so it's NOT AssetKid's fault. I just wish we can figure out what the new IG limits are or someone can come up with a solution.

I've tried reading other threads and everyone else is stumped. Ugh.
https://github.com/instaloader/instaloader/issues/828
https://github.com/instaloader/instaloader/issues/813

**Comment by supersick123** [comment]
> Recently, some of my accounts have been getting flagged at the _first login_. Oddly enough, this only happens when trying to login using Raider; logging in through the normal browser does NOT get flagged for suspicious activity. This takes place before any downloads have happened (ie. the account hasn't been used in 24 hours, but has definitely been used within the last 30 hours). It'll say "suspicious activity detected" in a red banner, then prompt to send a verification code. I sadly don't have a screenshot of this right now (and I'm lucky it hasn't happened since this morning), but the warning looks different than the above.

I got one again. This is what the red banner looks like.

<img width="1000" alt="Screen Shot 2020-12-06 at 7 15 47 PM copy" src="https://user-images.githubusercontent.com/63994830/101306170-04b09d80-37f9-11eb-827f-a80cb9ff73ef.png">

**Comment by suxxxbang** [comment]
I've done a few test and it seems that if your account doesn't follow anyone you're subscribing (to raider), it won't mark by ig as phising attempt.

My advice: use your blank account to update non-private ig account in Raider

**Comment by denbartman** [comment]
I installed Raider on a second PC. There i have added 2 accounts. (That i removed from the main pc)
With those 2 accounts i download only 10 private user accounts.
Still my user got flagged and i had to change password again.

I was hoping to secure my good accounts this way but that doesn't seem to help.

Just a thought, maybe the time intervals should be more random. So, not an api call every 50 seconds, but one after 30 seconds, the next after 60 seconds.... 

(@supersick123, I also did not get my code on my cellphone this time (2 tries)... When I changed it to mail, i got the code thru mail...)
